Code coverage
red-panda-productions/ipc-lib pull request #10
Opened 2022-03-24 16:51 UTC by KungFuDonkey

Creates code coverage (NOT BY DEFAULT) for the tests

2022-03-24 19:32 UTC, larsdekwant requested changes
Doesn't generate a new code coverage report when you edit and build a project sourcefile, only when you edit and build one of the files in the **test** folder.  You can of course force this by doing a Rebuild All, but I think it would be a better option to make it work for any Build All (Ctrl+Shift+B) if possible.

I do really like that it automatically opens the HTML report for you.

2022-03-25 10:10 UTC, KungFuDonkey commented
Could not get it to work without creating commands, so I changed it to a bat file that is created in the source dir. You can then run the bat file by typing ./coverage.bat, which will open the coverage report automatically again. The question that comes up now is: should I still make it an option that you can check in CMake? I don't think github actions would mind me creating a bat file, and we can run the bat file via a command that can store it in the output. I might have to remove the auto open command then from the bat file (as we can't see the screen of the github actions device anyway), but this can be a setting in cmake.

2022-03-25 10:54 UTC, suppergerrie2 approved these changes

2022-03-25 11:00 UTC, larsdekwant requested changes
Still only runs if the test files are rebuild. Otherwise the generated report will be empty.

2022-04-01 07:45 UTC, merged