V22F-542 Run code coverage over IPCLib
red-panda-productions/ipc-lib pull request #16
Opened 2022-04-23 18:19 UTC by KungFuDonkey

2022-04-24 09:32 UTC, KungFuDonkey commented
![image](https://user-images.githubusercontent.com/43845930/164969930-10dab206-e4dd-4ab7-b77a-fd0001339ce6.png)

2022-04-25 07:28 UTC, larsdekwant requested changes
Rename the `code coverage.yml` file to `code-coverage.yml` to avoid any possible errors with spaces in file names.

2022-04-25 07:28 UTC, larsdekwant commented on .github/workflows/ci.yml
> +
random extra line unrelated to this pull-request?
```suggestion
```

2022-04-25 11:53 UTC, suppergerrie2 approved these changes

2022-04-26 08:19 UTC, larsdekwant submitted a review, later dismissed

2022-04-26 08:19 UTC, larsdekwant commented on IPCTests/Utils.h
> +/// @return		  Whether the test failed or succeeded
This is not aligned correctly, probably due to tabs.

2022-04-26 08:19 UTC, larsdekwant commented on IPCTests/Utils.h
> +/// @param p_stringLength The length of the string (must be strictly smaller than the length of the buffer)
Same here, not aligned correctly due to tabs.

2022-04-26 10:37 UTC, merged