V22F-656 moved error code from receiving thread to main thread
red-panda-productions/ipc-lib pull request #18
Opened 2022-05-06 15:24 UTC by KungFuDonkey

This PR will support [this](https://github.com/red-panda-productions/SDALib/pull/23) PR, so that we can check the await data function for error codes. What is also nice to know is that this PR can now allow the user of the library to decide if they want to throw when an error occurs, as the library never throws an exception itself, but either catches the error internally or returns an error code.

2022-05-07 13:46 UTC, shoekzema requested changes

2022-05-07 13:46 UTC, shoekzema commented on IPCLib/Socket.cpp
> +int ReceivingThread::GetErrorCode() const
missing documentation

2022-05-07 13:46 UTC, shoekzema commented on IPCLib/Socket.cpp
> +int Socket::AwaitData(char* p_dataBuffer, int p_size)
update documentation to have a return

2022-05-07 13:46 UTC, shoekzema commented on IPCTests/SocketTest.cpp
> +TEST(SocketTests, ReceivingThreadThrow)
missing documentation

2022-05-09 09:43 UTC, shoekzema approved these changes

2022-05-09 10:00 UTC, suppergerrie2 approved these changes

2022-05-09 11:35 UTC, merged